/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InternalRouteImport } from './routes/internal'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as InternalIndexRouteImport } from './routes/internal/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as InternalLoginRouteImport } from './routes/internal/login'
import { Route as PublicProponerCharlaRouteImport } from './routes/_public/proponer-charla'
import { Route as PublicPrivacyPolicyRouteImport } from './routes/_public/privacy-policy'
import { Route as PublicNosotrosRouteImport } from './routes/_public/nosotros'
import { Route as PublicEventosRouteImport } from './routes/_public/eventos'
import { Route as PublicCodigoDeConductaRouteImport } from './routes/_public/codigo-de-conducta'
import { Route as InternalSpeakersIndexRouteImport } from './routes/internal/speakers/index'
import { Route as InternalProposalsIndexRouteImport } from './routes/internal/proposals/index'
import { Route as InternalSpeakersSpeakerIdRouteImport } from './routes/internal/speakers/$speakerId'
import { Route as InternalEventsEventIdRouteImport } from './routes/internal/events/$eventId'

const InternalRoute = InternalRouteImport.update({
  id: '/internal',
  path: '/internal',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalIndexRoute = InternalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InternalRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const InternalLoginRoute = InternalLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => InternalRoute,
} as any)
const PublicProponerCharlaRoute = PublicProponerCharlaRouteImport.update({
  id: '/proponer-charla',
  path: '/proponer-charla',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrivacyPolicyRoute = PublicPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicNosotrosRoute = PublicNosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => PublicRoute,
} as any)
const PublicEventosRoute = PublicEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCodigoDeConductaRoute = PublicCodigoDeConductaRouteImport.update({
  id: '/codigo-de-conducta',
  path: '/codigo-de-conducta',
  getParentRoute: () => PublicRoute,
} as any)
const InternalSpeakersIndexRoute = InternalSpeakersIndexRouteImport.update({
  id: '/speakers/',
  path: '/speakers/',
  getParentRoute: () => InternalRoute,
} as any)
const InternalProposalsIndexRoute = InternalProposalsIndexRouteImport.update({
  id: '/proposals/',
  path: '/proposals/',
  getParentRoute: () => InternalRoute,
} as any)
const InternalSpeakersSpeakerIdRoute =
  InternalSpeakersSpeakerIdRouteImport.update({
    id: '/speakers/$speakerId',
    path: '/speakers/$speakerId',
    getParentRoute: () => InternalRoute,
  } as any)
const InternalEventsEventIdRoute = InternalEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => InternalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/internal': typeof InternalRouteWithChildren
  '/codigo-de-conducta': typeof PublicCodigoDeConductaRoute
  '/eventos': typeof PublicEventosRoute
  '/nosotros': typeof PublicNosotrosRoute
  '/privacy-policy': typeof PublicPrivacyPolicyRoute
  '/proponer-charla': typeof PublicProponerCharlaRoute
  '/internal/login': typeof InternalLoginRoute
  '/': typeof PublicIndexRoute
  '/internal/': typeof InternalIndexRoute
  '/internal/events/$eventId': typeof InternalEventsEventIdRoute
  '/internal/speakers/$speakerId': typeof InternalSpeakersSpeakerIdRoute
  '/internal/proposals': typeof InternalProposalsIndexRoute
  '/internal/speakers': typeof InternalSpeakersIndexRoute
}
export interface FileRoutesByTo {
  '/codigo-de-conducta': typeof PublicCodigoDeConductaRoute
  '/eventos': typeof PublicEventosRoute
  '/nosotros': typeof PublicNosotrosRoute
  '/privacy-policy': typeof PublicPrivacyPolicyRoute
  '/proponer-charla': typeof PublicProponerCharlaRoute
  '/internal/login': typeof InternalLoginRoute
  '/': typeof PublicIndexRoute
  '/internal': typeof InternalIndexRoute
  '/internal/events/$eventId': typeof InternalEventsEventIdRoute
  '/internal/speakers/$speakerId': typeof InternalSpeakersSpeakerIdRoute
  '/internal/proposals': typeof InternalProposalsIndexRoute
  '/internal/speakers': typeof InternalSpeakersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/internal': typeof InternalRouteWithChildren
  '/_public/codigo-de-conducta': typeof PublicCodigoDeConductaRoute
  '/_public/eventos': typeof PublicEventosRoute
  '/_public/nosotros': typeof PublicNosotrosRoute
  '/_public/privacy-policy': typeof PublicPrivacyPolicyRoute
  '/_public/proponer-charla': typeof PublicProponerCharlaRoute
  '/internal/login': typeof InternalLoginRoute
  '/_public/': typeof PublicIndexRoute
  '/internal/': typeof InternalIndexRoute
  '/internal/events/$eventId': typeof InternalEventsEventIdRoute
  '/internal/speakers/$speakerId': typeof InternalSpeakersSpeakerIdRoute
  '/internal/proposals/': typeof InternalProposalsIndexRoute
  '/internal/speakers/': typeof InternalSpeakersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/internal'
    | '/codigo-de-conducta'
    | '/eventos'
    | '/nosotros'
    | '/privacy-policy'
    | '/proponer-charla'
    | '/internal/login'
    | '/'
    | '/internal/'
    | '/internal/events/$eventId'
    | '/internal/speakers/$speakerId'
    | '/internal/proposals'
    | '/internal/speakers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/codigo-de-conducta'
    | '/eventos'
    | '/nosotros'
    | '/privacy-policy'
    | '/proponer-charla'
    | '/internal/login'
    | '/'
    | '/internal'
    | '/internal/events/$eventId'
    | '/internal/speakers/$speakerId'
    | '/internal/proposals'
    | '/internal/speakers'
  id:
    | '__root__'
    | '/_public'
    | '/internal'
    | '/_public/codigo-de-conducta'
    | '/_public/eventos'
    | '/_public/nosotros'
    | '/_public/privacy-policy'
    | '/_public/proponer-charla'
    | '/internal/login'
    | '/_public/'
    | '/internal/'
    | '/internal/events/$eventId'
    | '/internal/speakers/$speakerId'
    | '/internal/proposals/'
    | '/internal/speakers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  InternalRoute: typeof InternalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/internal': {
      id: '/internal'
      path: '/internal'
      fullPath: '/internal'
      preLoaderRoute: typeof InternalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/': {
      id: '/internal/'
      path: '/'
      fullPath: '/internal/'
      preLoaderRoute: typeof InternalIndexRouteImport
      parentRoute: typeof InternalRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/internal/login': {
      id: '/internal/login'
      path: '/login'
      fullPath: '/internal/login'
      preLoaderRoute: typeof InternalLoginRouteImport
      parentRoute: typeof InternalRoute
    }
    '/_public/proponer-charla': {
      id: '/_public/proponer-charla'
      path: '/proponer-charla'
      fullPath: '/proponer-charla'
      preLoaderRoute: typeof PublicProponerCharlaRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/privacy-policy': {
      id: '/_public/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PublicPrivacyPolicyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/nosotros': {
      id: '/_public/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof PublicNosotrosRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/eventos': {
      id: '/_public/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof PublicEventosRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/codigo-de-conducta': {
      id: '/_public/codigo-de-conducta'
      path: '/codigo-de-conducta'
      fullPath: '/codigo-de-conducta'
      preLoaderRoute: typeof PublicCodigoDeConductaRouteImport
      parentRoute: typeof PublicRoute
    }
    '/internal/speakers/': {
      id: '/internal/speakers/'
      path: '/speakers'
      fullPath: '/internal/speakers'
      preLoaderRoute: typeof InternalSpeakersIndexRouteImport
      parentRoute: typeof InternalRoute
    }
    '/internal/proposals/': {
      id: '/internal/proposals/'
      path: '/proposals'
      fullPath: '/internal/proposals'
      preLoaderRoute: typeof InternalProposalsIndexRouteImport
      parentRoute: typeof InternalRoute
    }
    '/internal/speakers/$speakerId': {
      id: '/internal/speakers/$speakerId'
      path: '/speakers/$speakerId'
      fullPath: '/internal/speakers/$speakerId'
      preLoaderRoute: typeof InternalSpeakersSpeakerIdRouteImport
      parentRoute: typeof InternalRoute
    }
    '/internal/events/$eventId': {
      id: '/internal/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/internal/events/$eventId'
      preLoaderRoute: typeof InternalEventsEventIdRouteImport
      parentRoute: typeof InternalRoute
    }
  }
}

interface PublicRouteChildren {
  PublicCodigoDeConductaRoute: typeof PublicCodigoDeConductaRoute
  PublicEventosRoute: typeof PublicEventosRoute
  PublicNosotrosRoute: typeof PublicNosotrosRoute
  PublicPrivacyPolicyRoute: typeof PublicPrivacyPolicyRoute
  PublicProponerCharlaRoute: typeof PublicProponerCharlaRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicCodigoDeConductaRoute: PublicCodigoDeConductaRoute,
  PublicEventosRoute: PublicEventosRoute,
  PublicNosotrosRoute: PublicNosotrosRoute,
  PublicPrivacyPolicyRoute: PublicPrivacyPolicyRoute,
  PublicProponerCharlaRoute: PublicProponerCharlaRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface InternalRouteChildren {
  InternalLoginRoute: typeof InternalLoginRoute
  InternalIndexRoute: typeof InternalIndexRoute
  InternalEventsEventIdRoute: typeof InternalEventsEventIdRoute
  InternalSpeakersSpeakerIdRoute: typeof InternalSpeakersSpeakerIdRoute
  InternalProposalsIndexRoute: typeof InternalProposalsIndexRoute
  InternalSpeakersIndexRoute: typeof InternalSpeakersIndexRoute
}

const InternalRouteChildren: InternalRouteChildren = {
  InternalLoginRoute: InternalLoginRoute,
  InternalIndexRoute: InternalIndexRoute,
  InternalEventsEventIdRoute: InternalEventsEventIdRoute,
  InternalSpeakersSpeakerIdRoute: InternalSpeakersSpeakerIdRoute,
  InternalProposalsIndexRoute: InternalProposalsIndexRoute,
  InternalSpeakersIndexRoute: InternalSpeakersIndexRoute,
}

const InternalRouteWithChildren = InternalRoute._addFileChildren(
  InternalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  InternalRoute: InternalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
